-- Tables
CREATE TABLE EMPLOYEE (
EmployeeID VARCHAR(50) NOT NULL,
SSN VARCHAR(11) NOT NULL,
FName VARCHAR(50) NOT NULL,
LName VARCHAR(50) NOT NULL,
AuditLogFlag INT UNSIGNED NOT NULL,
PRIMARY KEY (EmployeeID),
UNIQUE(SSN));

CREATE TABLE DISTRICT (
DistrictNumber INT UNSIGNED NOT NULL,
PRIMARY KEY (DistrictNumber));

CREATE TABLE REPORT (
ReportName VARCHAR(80) NOT NULL,
PRIMARY KEY (ReportName));

CREATE TABLE ASSIGNED (
EmployeeID VARCHAR(50) NOT NULL,
DistrictNumber INT UNSIGNED NOT NULL,
PRIMARY KEY (DistrictNumber, EmployeeID),
FOREIGN KEY(EmployeeID) REFERENCES EMPLOYEE(EmployeeID)
FOREIGN KEY(DistrictNumber) REFERENCES DISTRICT(DistrictNumber));

CREATE TABLE AUDIT_LOG (
DateAndTime TIMESTAMP NOT NULL,
ReportViewed VARCHAR(80) NOT NULL,
EmployeeID VARCHAR(50) NOT NULL,
PRIMARY KEY (DateAndTime),
FOREIGN KEY(EmployeeID) REFERENCES EMPLOYEE(EmployeeID),
FOREIGN KEY(ReportViewed) REFERENCES REPORT(ReportName));

CREATE TABLE CITY (
CityName VARCHAR(50) NOT NULL,
StateName VARCHAR(50) NOT NULL,
PopulationSize INT UNSIGNED NOT NULL,
PRIMARY KEY (CityName, StateName));

CREATE TABLE STORE (
StoreNumber VARCHAR(50) NOT NULL,
StoreAddress VARCHAR(50) NOT NULL,
StorePhoneNumber VARCHAR(10) NOT NULL,
CityName VARCHAR(50) NOT NULL,
StateName VARCHAR(50) NOT NULL,
DistrictNumber INT UNSIGNED NOT NULL,
PRIMARY KEY (StoreNumber),
FOREIGN KEY (CityName, StateName) REFERENCES CITY(CityName, StateName),
FOREIGN KEY(DistrictNumber) REFERENCES DISTRICT(DistrictNumber));

CREATE TABLE PRODUCT (
PID VARCHAR(50) NOT NULL,
PName VARCHAR(50) NOT NULL,
RetailPrice DECIMAL(19, 2) NOT NULL,
Manufacturer VARCHAR(50) NOT NULL,
PRIMARY KEY (PID));

CREATE TABLE PRODUCT_CATEGORY (
PID VARCHAR(50) NOT NULL,
CategoryName VARCHAR(50) NOT NULL,
PRIMARY KEY (PID, CategoryName),
FOREIGN KEY(PID) REFERENCES PRODUCT(PID));

CREATE TABLE DISCOUNT (
DiscountedDate DATE NOT NULL,
DiscountPrice DECIMAL(19, 2) NOT NULL,
PID VARCHAR(50) NOT NULL,
PRIMARY KEY (DiscountedDate, PID),
FOREIGN KEY(PID) REFERENCES PRODUCT(PID));

CREATE TABLE HOLIDAY (
HDate DATE NOT NULL,
HName VARCHAR(50) NOT NULL,
AddedByEID VARCHAR(50) NOT NULL,
PRIMARY KEY (HDate),
FOREIGN KEY(AddedByEID) REFERENCES EMPLOYEE(EmployeeID));

CREATE TABLE SALE (
SaleID VARCHAR(50) NOT NULL,
PID VARCHAR(50) NOT NULL,
SaleDate DATE NOT NULL,
SalePrice DECIMAL(19, 2) NOT NULL,
Quantity INT UNSIGNED NOT NULL,
StoreNumber VARCHAR(50) NOT NULL,
PRIMARY KEY (SaleID),
FOREIGN KEY(PID) REFERENCES PRODUCT(PID),
FOREIGN KEY(StoreNumber) REFERENCES STORE(StoreNumber));